bockus/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from bockus.views import HomeView
import books.urls
from books.views import LibrarySearchView
import readers.urls

from invites.views import (
    CreateInviteView,
    AcceptInviteView,
    ChangePasswordView,
)

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(
        r'^set-password/$',
        ChangePasswordView.as_view(),
        name='set-password',
    ),
    url(r'^invites/add$', CreateInviteView.as_view(), name='create-invite'),
    url(
        r'^invites/accept/(?P<key>[\w-]+)/$',
        AcceptInviteView.as_view(),
        name='accept-invite',
    ),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    url(r'^books/', include(books.urls.bookpatterns)),
    url(r'^series/', include(books.urls.seriespatterns)),
    url(r'^readers/', include(readers.urls.readerpatterns)),
    url(r'^shelves/', include(books.urls.shelfpatterns)),
    url(r'^search/', LibrarySearchView.as_view(), name='search'),
    url(r'^$', HomeView.as_view(), name='home-view'),
]

books/urls.py
from django.conf.urls import patterns, include, url

import books.views

bookpatterns = patterns('',
    url(r'^$', books.views.BookListView.as_view(), name='book-list'),
    url(
        r'^(?P<pk>\d+)/$',
        books.views.BookView.as_view(),
        name='book-detail',
    ),
    url(
        r'^(?P<pk>\d+)/send/(?P<reader>\d+)/$',
        books.views.SendBookView.as_view(),
        name='book-send',
    ),
    # url(
    #     r'^new$',
    #     books.views.CreateBookView.as_view(),
    #     name='book-new',
    # ),
    url(
        r'^(?P<pk>\d+)/edit/$',
        books.views.EditBookView.as_view(),
        name='book-edit',
    ),
    url(
        r'^(?P<pk>\d+)/delete/$',
        books.views.DeleteBookView.as_view(),
        name='book-delete',
    ),
    url(
        r'^import/$',
        books.views.ImportBooksView.as_view(),
        name='books-import',
    ),
    url(
        r'^merge/$',
        books.views.MergeBookView.as_view(),
        name='books-merge',
    ),
    url(r'^shelve/$',
        books.views.ShelveBooksView.as_view(),
        name='books-shelve',
    ),
    url(r'^delete/$',
        books.views.DeleteBooksView.as_view(),
        name='books-delete',
    ),
)

seriespatterns = patterns('',
    url(r'^$', books.views.SeriesListView.as_view(), name='series-list'),
    url(
        r'^(?P<pk>\d+)/$',
        books.views.SeriesView.as_view(),
        name='series-detail',
    ),
    url(
        r'^new$',
        books.views.CreateSeriesView.as_view(),
        name='series-create',
    ),
    url(
        r'^edit/(?P<pk>\d+)/$',
        books.views.EditSeriesView.as_view(),
        name='series-edit',
    ),
    url(
        r'^delete/(?P<pk>\d+)/$',
        books.views.DeleteSeriesView.as_view(),
        name='series-delete',
    ),
)

shelfpatterns = patterns('',
    url(r'^$', books.views.ShelfListView.as_view(), name='shelf-list'),
    url(
        r'^(?P<pk>\d+)/$',
        books.views.ShelfView.as_view(),
        name='shelf-detail',
    ),
    url(
        r'^new$',
        books.views.CreateShelfView.as_view(),
        name='shelf-create',
    ),
    url(
        r'^edit/(?P<pk>\d+)/$',
        books.views.EditShelfView.as_view(),
        name='shelf-edit',
    ),
    url(
        r'^delete/(?P<pk>\d+)/$',
        books.views.DeleteShelfView.as_view(),
        name='shelf-delete',
    ),
    url(
        r'^lastweek$',
        books.views.LastWeekShelfView.as_view(),
        name='shelf-last-week',
    ),
    url(
        r'^lastmonth$',
        books.views.LastMonthShelfView.as_view(),
        name='shelf-last-month',
    ),
)

books/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.timezone import now
from jsonfield import JSONField
from model_utils.models import TimeStampedModel
from libraries.models import Library
from readers.models import Reader


class Book(TimeStampedModel):

    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, null=True, blank=True)
    series = models.ForeignKey('Series', null=True, blank=True)
    number_in_series = models.IntegerField(null=True, blank=True)
    library = models.ForeignKey(Library)
    added_by = models.ForeignKey(User)
    meta = JSONField(blank=True)

    def __str__(self):
        string = self.title
        if self.author:
            string = "{} by {}".format(string, self.author)
        if self.series:
            if self.number_in_series:
                string = "{} ({} {})".format(
                    string,
                    self.series.name,
                    self.number_in_series,
                )
            else:
                string = "{} ({})".format(string, self.series.name)
        return string

    def get_absolute_url(self):
        return reverse('book-detail', kwargs={'pk': self.id})

    def to_dict(self):
        blob = {
            'title': self.title,
            'author': self.author,
            'library': self.library.id,
            'added_by': self.added_by.id,
            'meta': self.meta,
        }
        if self.series:
            blob['series'] = self.series.id
        if self.number_in_series:
            blob['number_in_series'] = self.number_in_series
        return blob

    def bookfiles(self):
        return BookFileVersion.objects.filter(book=self)

    @property
    def is_book(self):
        return True

    @property
    def epub(self):
        if not hasattr(self, '_epub') or not self._epub:
            try:
                self._epub = BookFileVersion.objects.filter(
                    book=self,
                    filetype=BookFileVersion.EPUB,
                )[0]
            except (BookFileVersion.DoesNotExist, IndexError):
                self._epub = None
        return self._epub

    @property
    def pdf(self):
        if not hasattr(self, '_pdf') or not self._pdf:
            try:
                self._pdf = BookFileVersion.objects.filter(
                    book=self,
                    filetype=BookFileVersion.PDF,
                )[0]
            except (BookFileVersion.DoesNotExist, IndexError):
                self._pdf = None
        return self._pdf

    @property
    def mobi(self):
        if not hasattr(self, '_mobi') or not self._mobi:
            try:
                self._mobi = BookFileVersion.objects.filter(
                    book=self,
                    filetype=BookFileVersion.MOBI,
                )[0]
            except (BookFileVersion.DoesNotExist, IndexError):
                self._mobi =  None
        return self._mobi


    def get_version_for_kindle(self):
        if self.mobi:
            return self.mobi
        return self.pdf

    def get_version_for_other(self):
        if self.epub:
            return self.epub
        return self.pdf

    def last_emailed(self, user):
        try:
            book_email = BookEmail.objects.filter(
                book_file__in=self.bookfiles(),
                status=BookEmail.SENT,
                reader__user=user,
            ).order_by('-created')[0]
            return book_email.created
        except (BookEmail.DoesNotExist, IndexError):
            return None


class BookFileVersion(TimeStampedModel):
    DROPBOX = 'dropbox'
    STORAGE_PROVIDERS = (
        ('dropbox', 'dropbox'),
    )

    EPUB = 'epub'
    PDF = 'pdf'
    MOBI = 'mobi'
    FILETYPES = (
        ('epub', 'epub'),
        ('pdf', 'pdf'),
        ('mobi', 'mobi'),
    )

    book = models.ForeignKey('Book')
    filetype = models.CharField(max_length=10, choices=FILETYPES)
    storage_provider = models.CharField(
        max_length=10,
        choices=STORAGE_PROVIDERS,
        default=DROPBOX,
    )
    path = models.TextField(null=True)
    meta = JSONField()

    def __str__(self):
        return "{} - {}".format(self.book.title, self.filetype)


class BookEmail(TimeStampedModel):
    PENDING = 'pending'
    PROCESSING = 'processing'
    SENT = 'sent'
    ERROR = 'error'
    STATUSES = (
        ('pending', 'pending'),
        ('processing', 'processing'),
        ('sent', 'sent'),
        ('error', 'error'),
    )

    book_file = models.ForeignKey('BookFileVersion')
    reader = models.ForeignKey(Reader,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    status = models.CharField(
        max_length=20,
        choices=STATUSES,
        default=PENDING,
    )

    def __str__(self):
        return "{}: {} to {}".format(
            self.status, self.book_file.id, self.reader,
        )


class Series(TimeStampedModel):

    name = models.CharField(max_length=255)
    author = models.CharField(max_length=255, null=True, blank=True)
    library = models.ForeignKey(Library)
    meta = JSONField(blank=True)

    def __str__(self):
        return "{} by {}".format(self.name, self.author)

    def get_absolute_url(self):
        return reverse('series-detail', kwargs={'pk': self.id})

    @property
    def is_series(self):
        return True

    class Meta:
        verbose_name_plural = 'series'


class Shelf(TimeStampedModel):

    name = models.CharField(max_length=255)
    library = models.ForeignKey(Library)
    meta = JSONField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shelf-detail', kwargs={'pk':self.id})

    class Meta:
        verbose_name_plural = 'shelves'


class BookOnShelf(TimeStampedModel):

    book = models.ForeignKey('Book')
    shelf = models.ForeignKey('Shelf')

    def __str__(self):
        return '"{}" on {}'.format(self.book, self.shelf)

    class Meta:
        verbose_name_plural = 'books on shelves'

books/forms.py
import dropbox
from django import forms
from books.models import Series


class ImportForm(forms.Form):

    def __init__(self, *args, **kwargs):
        token = kwargs.pop('token')
        client = kwargs.pop('client')
        super(ImportForm, self).__init__(*args, **kwargs)
        choices = [('select_all_option', 'Select All')]
        metadata = client.metadata('/')
        directories = [(item.get('path'), item.get('path')) for item in metadata.get('contents') if item.get('is_dir')]
        choices += directories

        self.fields['folders'] = forms.MultipleChoiceField(
            required=True,
            choices=choices,
            widget=forms.CheckboxSelectMultiple(),
        )


class BookForm(forms.Form):

    author = forms.CharField(max_length=255,required=False)

    def __init__(self, *args, **kwargs):
        library = kwargs.pop('library')
        super(BookForm, self).__init__(*args, **kwargs)
        series_choices = [
            (series.id, series.series) for series in Series.objects.filter(library==library)
        ]
        self.fields['series'] = forms.ChoiceField(
            required=False,
            choices=series_choices,
        )

bockus/books/views.py
import dropbox

from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.http import Http404
from django.shortcuts import (
    get_object_or_404,
    redirect,
)
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
    View,
)

from allauth.socialaccount.models import SocialApp, SocialToken

from .models import (
    Book,
    BookFileVersion,
)

from readers.models import Reader


class BookListView(ListView):

    model = Book
    template_name = "book_list.html"


class BookView(DetailView):

    model = Book
    template_name = "book.html"

    def get_context_data(self, **kwargs):
        context = super(BookView, self).get_context_data(**kwargs)
        context['readers'] = Reader.objects.filter(user=self.request.user)

        return context


class CreateBookView(CreateView):

    model = Book
    template_name = "add_or_edit_book.html"
    fields = ['title',]

    def get_success_url(self):
        return reverse('book-list')


class EditBookView(UpdateView):

    model = Book
    template_name = "add_or_edit_book.html"
    fields = ['title',]

    def get_success_url(self):
        return reverse('book-detail', args=[self.object.pk])

    def get_context_data(self, **kwargs):
        context = super(EditBookView, self).get_context_data(**kwargs)
        context['action'] = reverse(
            'book-edit',
            kwargs={'pk': self.get_object().id},
        )

        return context

    def form_valid(self, form):
        messages.success(self.request, "{} updated".format(self.object))

        return super(EditBookView, self).form_valid(form)


class DeleteBookView(DeleteView):

    model = Book
    template_name = "book_delete.html"

    def get_success_url(self):
        return reverse('book-list')

    def form_valid(self, form):
        messages.success(self.request, "{} deleted".format(self.object))

        return super(DeleteBookView, self).form_valid(form)


class SendBookView(View):

    def get(self, request, *args, **kwargs):
        book = get_object_or_404(Book.objects, pk=kwargs.get('pk'))
        reader = get_object_or_404(Reader.objects, pk=kwargs.get('reader'))
        book_file_version = BookFileVersion.objects.filter(
            book=book,
        )[0]
        book_file_path = book_file_version.path
        try:
            dropbox_app_creds = SocialApp.objects.filter(
                provider='dropbox_oauth2'
            )[0]
            token = SocialToken.objects.get(
                account__user=request.user,
                app__provider='dropbox_oauth2'
            ).token
        except:
            raise Http404()
        client = dropbox.client.DropboxClient(token)

        message = EmailMessage(
            subject='A book for you!',
            body=book.title,
            from_email="books@inkpebble.com",
            to=[reader.email,],
        )
        f, metadata = client.get_file_and_metadata(book_file_path)
        message.attach(
            'book.{}'.format(book_file_version.filetype),
            f.read(),
            metadata.get('mime_type'),
        )
        message.send()
        messages.add_message(request, messages.SUCCESS, 'Book emailed!')
        return redirect(book)

books/views/search_views.py
from django.conf import settings
from django.http import Http404
from haystack.generic_views import SearchView
from libraries.models import Library


class LibrarySearchView(SearchView):
    """ Searches across whole Library

    Restricts search to books and series in one Library.
    """

    paginate_by = settings.LIST_PAGINATE_BY
    paginate_orphans = settings.LIST_PAGINATE_ORPHANS

    def get_queryset(self):
        queryset = super(LibrarySearchView, self).get_queryset()
        try:
            library = Library.objects.get(librarian__user=self.request.user)
        except Library.DoesNotExist:
            raise Http404()
        return queryset.filter(library=library.id)

books/views/series_views.py
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from books.models import (
    Book,
    Series,
)

from books.views import (
    SEARCH_UPDATE_MESSAGE,
    LibraryMixin,
)

from readers.models import Reader


class SeriesListView(LibraryMixin, ListView):

    model = Series
    template_name = "series_list.html"


class SeriesView(LibraryMixin, DetailView):

    model = Series
    template_name = "series.html"
    paginate_by = 25
    paginate_orphans = 5

    def get_context_data(self, **kwargs):
        context = super(SeriesView, self).get_context_data(**kwargs)
        context['books'] = Book.objects.filter(
            series=self.get_object(),
        ).order_by(
            'number_in_series',
        )
        return context

class CreateSeriesView(LibraryMixin, CreateView):

    model = Series
    template_name = "series_edit.html"
    fields = ['name', 'author']

    def get_success_url(self):
        return reverse('series-list')

    def get_context_data(self, **kwargs):
        context = super(CreateSeriesView, self).get_context_data(**kwargs)
        context['action'] = reverse('series-create')

        return context


class EditSeriesView(LibraryMixin, UpdateView):

    model = Series
    template_name = "series_edit.html"
    fields = ['name', 'author']

    def get_success_url(self):
        return reverse(
            'series-detail',
            kwargs={'pk': self.object.id}
        )

    def get_context_data(self, **kwargs):
        context = super(EditSeriesView, self).get_context_data(**kwargs)
        context['action'] = reverse(
            'series-edit',
            kwargs={'pk': self.object.id},
        )

        return context

    def form_valid(self, form):
        messages.success(self.request, "{} updated. {}".format(
            self.object, SEARCH_UPDATE_MESSAGE
        ))

        return super(EditSeriesView, self).form_valid(form)


class DeleteSeriesView(LibraryMixin, DeleteView):

    model = Series
    template_name = "series_delete.html"

    def get_success_url(self):
        return reverse('series-list')

    def form_valid(self, form):
        messages.success(self.request, "{} deleted. {}".format(
            self.object, SEARCH_UPDATE_MESSAGE
        ))

        return super(DeleteSeriesView, self).form_valid(form)

books/templates/add_or_edit_series.html
{% extends "base.html" %}

{% block heading %}
{{ block.super }} - <a href="{% url "series-list" %}">Series</a> - 
{% if series %}
Edit "{{ series }}"
{% else %}
Add Series
{% endif %}
{% endblock %}
{% block content %}
<form action="{{ action }}" method="POST">
  {% csrf_token %}
  <ul>
    {{ form.as_ul }}
  </ul>
  <input id="save_series" type="submit" value="Save" />
</form>

<a href="{% url "series-list" %}">Series List</a>
{% endblock %}

books/templates/book.html
{% extends "base.html" %}

{% block heading %}{{ block.super }} - <a href="{% url "book-list" %}">Books</a> - {{ book }}{% endblock %}
{% block content %}

<p><a href="{% url "book-edit" pk=book.id %}">Edit</a> | <a href="{% url "book-delete" pk=book.id %}">Delete</a></p>
<p>Author: {% if book.author %}{{ book.author }}{% endif %}</p>
<p>Series: {% if book.series %}{{ book.series }}{% endif %}</p>
<p>Number in series: {% if book.number_in_series %}{{ book.number_in_series }}{% endif %}</p>
<p>
    Available in:
    <ul>
        {% if book.mobi %}<li>mobi (Kindle-compatible)</li>{% endif %}
        {% if book.epub %}<li>epub (iBooks, Kobo compatible)</li>{% endif %}
        {% if book.pdf %}<li>pdf (Compatible with most readers)</li>{% endif %}
    </ul>
</p>
{% if kindles %}
    {% if can_send_to_kindle %}
    {% for kindle in kindles %}
    <p><a href="{% url "book-send" pk=book.id reader=kindle.id %}">Send Book to {{ kindle }}</a></p>
    {% endfor %}
    {% else %}
    <p>You have kindles registered, but this book doesn't have a kindle-compatible file in your dropbox. Try adding one and re-importing, or <a href="{% url "reader-create" %}?next={% url "book-detail" pk=book.id %}">add a different reader</a>.</p>
    {% endif %}
{% elif other_readers %}
    {% if can_send_to_other %}
    {% for reader in other_readers %}
    <p><a href="{% url "book-send" pk=book.id reader=reader.id %}">Send Book to {{ reader }}</a></p>
    {% endfor %}
    {% else %}
    <p>You have iBooks registered, but this book doesn't have a iBooks-compatible file in your dropbox. Try adding one and re-importing, or <a href="{% url "reader-create" %}?next={% url "book-detail" pk=book.id %}">add a different reader</a>.</p>
    {% endif %}
{% else %}
<p>Hmm... No eBook readers attached to this account. Why not <a href="{% url "reader-create" %}?next={% url "book-detail" pk=book.id %}">add one</a>?</p>
{% endif %}
<form action="{% url "book-detail" pk=book.id %}" method="POST">
    {% csrf_token %}
    <p>
        <label for="id_shelf">{{ form.fields.shelf.label }}</label>
        <select id="id_shelf" name="shelf">
        {% for id, shelf in form.fields.shelf.choices %}
            <option value="{{ id }}">{{ shelf }}</option>
        {% endfor %}
        </select>
        <input type="submit" value="Submit" />
    </p>
</form>
{% endblock %}

books/templates/book_delete.html
{% extends "base.html" %}

{% block heading %}{{ block.super }} - <a href="{% url "book-list" %}">Books</a> - Delete Book{% endblock %}
{% block content %}

<p>Are you sure you want to delete the book "{{ book }}"?</p>
<p>(Note, this will not delete ebook files)</p>

<form action="{% url "book-delete" pk=book.id %}" method="POST">
  {% csrf_token %}

  <input type="submit" value="Yes, delete." />
  <a href="{% url "book-list" %}">No, cancel.</a>
</form>
{% endblock %}

books/templates/book_edit.html
{% extends "base.html" %}

{% block heading %}
{{ block.super }} - <a href="{% url "book-list" %}">Books</a> - 
{% if book %}
Edit "{{ book }}"
{% else %}
Add Book
{% endif %}
{% endblock %}

{% block content %}
<form action="{{ action }}" method="POST">
  {% csrf_token %}
  <ul>
    {{ form.as_p }}
  </ul>
  <input id="save_book" type="submit" value="Save" />
</form>
{% endblock %}

books/templates/book_list.html
{% extends "base.html" %}
{% load humanize %}

{% block heading %}{{ block.super }} - Books{% endblock %}
{% block content %}
{% if object_list %}
<form action="{% url "book-list" %}" method="POST">
    {% csrf_token %}
    <input id="id_page" name="page" value="{{ page_obj.number }}" type="hidden" />
    <ul>{% for id, book_obj in form.fields.books.choices %}
        <li>
            <input value="{{ id }}" name="books" type="checkbox" /> 
            <a href="{% url "book-detail" pk=id %}">{{ book_obj.book }}</a> (<a href="{% url "book-edit" pk=id %}">Edit</a> | <a href="{% url "book-delete" pk=id %}">Delete</a>)
            {% if book_obj.last_emailed %}Last read {{ book_obj.last_emailed | naturalday}}{% endif %}
        </li>
    {% endfor %}</ul>
    {{ form.actions }} <input id="save_book" type="submit" value="Submit" />
</form>
{% include "page_controls_snippet.html" %}
{% else %}
<p>No books in library!</p>
{% if running_imports %}
<p>We're currently importing some books for you, and we will send you en email when they're ready.</p>
{% else %}
<p><a href="{% url "books-import" %}">Import some books!</a></p>
{% endif %}
{% endif %}
{% endblock %}

books/templates/books_delete.html
{% extends "base.html" %}

{% block heading %}{{ block.super }} - <a href="{% url "book-list" %}">Books</a> - Delete Books{% endblock %}
{% block content %}

<p>Are you sure you want to delete the following books?</p>
<ul>
{% for book in books %}
    <li>{{ book }}</li>
{% endfor %}
</ul>

<form action="{% url "books-delete" %}" method="POST">
  {% csrf_token %}

  <input type="submit" value="Yes, delete." />
  <a href="{% url "book-list" %}">No, cancel.</a>
</form>
{% endblock %}

books/templates/page_controls_snippet.html
{% if page_obj.has_previous or page_obj.has_next %}
<div>
    {% if page_obj.number != 1 %}<a href="?page=1">&laquo; First</a> | {% endif %}
    {% if page_obj.has_previous %}<a href="?page={{ page_obj.previous_page_number }}">&lt; Previous</a> | {% endif %}
    <span>Page {{ page_obj.number }} of {{ paginator.num_pages }}</span>{% if page_obj.has_next %} | {% endif %}
    {% if page_obj.has_next %}<a href="?page={{ page_obj.next_page_number }}">Next &gt;</a> | {% endif %}
    {% if page_obj.number != paginator.num_pages %}<a href="?page={{ paginator.num_pages }}">Last &raquo;</a>{% endif %}
</div>
{% endif %}

books/templates/series_delete.html
{% extends "base.html" %}

{% block heading %}{{ block.super }} - <a href="{% url "series-list" %}">Series</a> - Delete Series{% endblock %}
{% block content %}

<p>Are you sure you want to delete the series "{{ series }}"?</p>

<form action="{% url "series-delete" pk=series.id %}" method="POST">
  {% csrf_token %}

  <input type="submit" value="Yes, delete." />
  <a href="{% url "series-list" %}">No, cancel.</a>
</form>
{% endblock %}

books/templates/series_list.html
{% extends "base.html" %}

{% block heading %}{{ block.super }} - Series{% endblock %}
{% block content %}
<ul>
  {% for series in object_list %}
    <li class="series"><a href="{{ series.get_absolute_url }}">{{ series }}</a> (<a href="{% url "series-edit" pk=series.id %}">Edit</a> | <a href="{% url "series-delete" pk=series.id %}">Delete</a>)</li>
  {% endfor %}
</ul>
{% if page_obj.has_previous or page_obj.has_next %}
    <div>
        {% if page_obj.has_previous %}<a href="?page={{ page_obj.previous_page_number }}">{% endif %}&laquo; Previous{% if page_obj.has_previous %}</a>{% endif %}
        |
        {% if page_obj.has_next %}<a href="?page={{ page_obj.next_page_number }}">{% endif %}Next &raquo;{% if page_obj.has_next %}</a>{% endif %}
    </div>
{% endif %}
{% endblock %}

books/templates/shelf.html
{% extends "base.html" %}

{% block heading %}
{% if shelf %}
{{ block.super }} - <a href="{% url "shelf-list" %}">Shelves</a> - {{ shelf }}
{% else %}
{{ block.super }} - <a href="{% url "shelf-list" %}">Shelves</a> - {{ shelf_name }}
{% endif %}
{% endblock %}
{% block content %}
{% include "book_list_snippet.html" %}
{% include "page_controls_snippet.html" %}
{% if shelf %}
<p><a href="{% url "shelf-edit" pk=shelf.id %}">Edit shelf</a> | <a href="{% url "shelf-delete" pk=shelf.id %}">Delete shelf</a></p>
{% endif %}
{% endblock %}

books/templates/shelf_delete.html
{% extends "base.html" %}

{% block heading %}{{ block.super }} - <a href="{% url "shelf-list" %}">Shelves</a> - Delete Shelf{% endblock %}
{% block content %}

<p>Are you sure you want to delete the shelf "{{ shelf }}"?</p>

<form action="{% url "shelf-delete" pk=shelf.id %}" method="POST">
  {% csrf_token %}

  <input type="submit" value="Yes, delete." />
  <a href="{% url "shelf-list" %}">No, cancel.</a>
</form>
{% endblock %}

books/templates/shelf_edit.html
{% extends "base.html" %}

{% block heading %}
{{ block.super }} - <a href="{% url "shelf-list" %}">Shelves</a> - 
{% if shelf %}
Edit "{{ shelf }}"
{% else %}
Add Shelf
{% endif %}
{% endblock %}
{% block content %}
<form action="{{ action }}" method="POST">
  {% csrf_token %}
  <ul>
    {{ form.as_ul }}
  </ul>
  <input id="save_shelf" type="submit" value="Save" />
</form>

<a href="{% url "shelf-list" %}">Shelf List</a>
{% endblock %}

books/templates/shelf_list.html
{% extends "base.html" %}

{% block heading %}{{ block.super }} - Shelves{% endblock %}
{% block content %}
{% if not object_list %}<p>Shelves are collections of books that you curate in any way that makes sense to you. We've provided some default shelves to get you started.</p>{% endif %}
<ul>
    <li class="shelf"><a href="{% url "shelf-last-week" %}">Added in Last Week</a>
    <li class="shelf"><a href="{% url "shelf-last-month" %}">Added in Last Month</a></li>
  {% for shelf in object_list %}
    <li class="shelf"><a href="{{ shelf.get_absolute_url }}">{{ shelf }}</a> (<a href="{% url "shelf-edit" pk=shelf.id %}">Edit</a> | <a href="{% url "shelf-delete" pk=shelf.id %}">Delete</a>)</li>
  {% endfor %}
</ul>
{% endblock %}

books/templates/shelve_books.html
{% extends "base.html" %}

{% block heading %}{{ block.super }} - <a href="{% url "book-list" %}">Books</a> - Shelve Books{% endblock %}
{% block content %}

<p>Add these books...</p>
<ul>
{% for book in books %}
    <li>{{ book }}</li>
{% endfor %}
</ul>
<p>...to which shelf?
<form action="{% url "books-shelve" %}" method="POST">
  {% csrf_token %}

  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>
<p><a href="{% url "book-list" %}">Cancel.</a></p>
{% endblock %}